HttpServer:
  port: ':8081'
  timeout: '30s'
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

Database:
  host: 'localhost'
  port: '5432'
  db_name: 'postgres'
  username: 'postgres'
  password: "postgres"

Auth:
  JwtSecretKey: "AllYourBase"
  PasswordSecretKey: "dsadjflshfjghfdjkggfdj21321"
  TimeToLive: 15m

GrpcServer:
  Port: ":9090"

Redis:
  address: 'localhost:6379'
  TimeToLive: 24h