basePath: /
definitions:
  api.Error:
    properties:
      message:
        type: string
    type: object
  api.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entity.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      firstname:
        type: string
      id:
        type: string
      isVerified:
        type: boolean
      lastname:
        type: string
      password:
        type: string
    required:
    - email
    - firstname
    - lastname
    - password
    type: object
  github_com_murat96k_kitaptar_kz_internal_auth_handler_dto.RefreshInput:
    properties:
      token:
        type: string
    required:
    - token
    type: object
host: localhost:8080
info:
  contact: {}
  description: Service for authorization for users
  title: kitaptar.kz Auth service
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Sign in to the app with auth service
      parameters:
      - description: req body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Login to app
      tags:
      - auth
  /refresh:
    post:
      consumes:
      - application/json
      description: Refresh access and refresh token by refresh token
      parameters:
      - description: req body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/github_com_murat96k_kitaptar_kz_internal_auth_handler_dto.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Refresh token
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: req body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Create user
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
