HttpServer:
  port: ':8080'
  timeout: '30s'
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

Database:
  host: 'localhost'
  port: '5432'
  db_name: 'postgres'
  username: 'postgres'
  password: "postgres"

Auth:
  JwtSecretKey: "AllYourBase"
  PasswordSecretKey: "dsadjflshfjghfdjkggfdj21321"
  TimeToLive: 15m

Redis:
  address: 'localhost:6379'
  TimeToLive: 24h

Transport:
  User:
    Host: http://127.0.0.1:9235
    Timeout: 5s
  UserGrpc:
    Host: localhost:9090
    Port: ':9090'

# TODO Implement kafka
#Kafka:
#  Brokers:
#    - 127.0.0.1:19092
#  Producer:
#    topic: "user-verification"
#  Consumer:
#    topics:
#      - "user-verification"